Outcome:

1. Introduction to NumPy
    
1.1 : History of NumPy
1.2 : Functionality of NumPy
1.3 : Why NumPy needs
1.4 : Applications of NumPy
1.5 : Types of NumPy array
1.6 : Basic NumPy array creation
1.7 : NumPy Array Attributes
1.8 : Drawback of NumPy array


1.1: History of NumPy
 - NumPy Short for Numerical Python, is a powerful open source library python use for scientific computing.
 - NumPy library mainly focus on the NumPy arrays
 - It was created in 2005 by Travis oliphant.

1.2: Functionality of NumPy
  - N-Dimensional array Creation and initialization
  - Array Manipulation
  - Mathematical operations
  - Broadcasting
  - Linear Algebra Operations
  - Statistics and Aggregation Functions
  - Random Number Generation
  - Fourier Transform and signal processing
  - Input and Output Functions
    etc.
   
1.3: Why NumPy needs
  
  - Efficiency      : NumPy is faster(50x) than traditional Python lists for mathematical operations.
  
  - Flexibility     : NumPy allows for efficient handling of multidimensional arrays and matrices.
  
  - Compatibility   : NumPy is compatible with a wide range(600) of Python libraries and tools.
  
  - memory efficient: consume less memory than the traditional list.


1.4: Applications of NumPy
  - Data Science :
            Used for data cleaning, transformation and analysis.
  
  - Image Processing:
           Helps in manipulating image representation as arrays.

  - Simulations:
           Useful in Scientific simulation, such as modeling physical systems
  
  - Financial Analysis

  - etc

1.5 : Types of NumPy array
----------------------------


outcomes:
    - Definition of Array
    - Array Needs
    - Type of Array
    - basic array creation



Definition of Array:
   An array is linear static data structure that stores a collection of elements, typically of the same data type, in a contiguous block of memory.

Array Needs:
    More efficient than python lists for numerical operations because they are implemented in c and allow vectorized operations.

Type of Array:
    1. 0-D array(scalar)
    2. 1-D array(vector)
    3. 2-D array(matrix)
    4. n-D array(tensor)

In [4]:
''' 
1.6 : Basic NumPy array creation
---------------------------------

# 1. 0-D array(scalar)
  
- A constant value 
- only value no direction.

Syntax:
scalar = np.array(value) 
 
'''
print("Basic 1-d array create")
import numpy as np

scalar = np.array(10) 

print("Example one \n------------\n")
# Create a scalar numpy array
print(scalar)  # Output: [10]

print("type: ",type(scalar))  # type of array(scalar)
print("Dimension: ",scalar.ndim)   #  Dimension of array


Basic 1-d array create
Example one 
------------

10
type:  <class 'numpy.ndarray'>
Dimension:  0


In [ ]:
# 2. 1-D array(vector)
'''  
   - A single row or column of elements.
   - only one subscription([])

Structure:
   in the code:
        [-1, 2, 3]
          or 

        [-1]
         [2]
         [3]

    in the memory:
        ______________
        | -1 | 2 | 3 |
        ______________

Syntax:
arr_1D = np.array(object, dtype = None)

here, 
     - object: any iterable (like list, tuple, array etc.) or input data
     - dtype: data type of the array. specifies the desired data type of the array elements(eg. int32, float64)


     
         
'''
# eg_01: Creating a 1-d array form a list
print("NumPy 1-d Array: ")

arr_1d = np.array([1, 2, 3, 4])

print("Example one: ")
print(arr_1d)

print("type: ",type(arr_1d))   # type of array (numpy.ndarray)
print("Dimension: ",arr_1d.ndim)   #  Dimension of array(1)

# another way to create array form existing list
print("Example Two: ")

lst = [10, 20, 30, 40]
arr1_1d = np.array(lst)
print(arr1_1d)


# eg_03: Creating a 1-d array from a tuple
print("Example Three: ")
arr2_1d = np.array((100, 200, 300, 400))

print(arr2_1d)
print("type: ",type(arr2_1d))


# eg_04: Creating a 1-d array from specifying a data type
print("Example Four: ")
arr_float = np.array([-10, -20, -30, -40, -50], dtype = float)

print(arr_float)
print("type: ", type(arr_float)) # type of array
print("Dimension: ",arr_float.ndim)  #  Dimension of array




NumPy 1-d Array: 
Example one: 
[1 2 3 4]
type:  <class 'numpy.ndarray'>
Dimension:  1
Example Two: 
[10 20 30 40]
Example Three: 
[100 200 300 400]
type:  <class 'numpy.ndarray'>
Example Four: 
[-10. -20. -30. -40. -50.]
type:  <class 'numpy.ndarray'>
Dimension:  1


3. 2-D array(matrix)
   
   - A rectangular collection of numbers.
   - A matrix is a 2-dimensional array.
   - it can be represented in the form of rows and columns.
   - it have two subscripts([[ ]])

Structure:
   in code:                            
      [[1, 2, 3],                                  
      [4, 5, 6],
      [7, 8, 9]]

   in the memory format:
       _____________
       | [1| 2| 3] |  
       |____________
       | [7| 8| 9] |
       |____________
       
Syntax:
   arr_2D = np.array(object, dtype = None)
   
  

In [4]:
# # create a 2D array with 3 rows and 3 columns.
print("NumPy 2-d Array Creation: ")

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Example one: ")

print(arr_2d)
print("Type      : ",type(arr_2d))
print("Dimension : ", arr_2d.ndim)     #  Dimension of array


# another way to create with existing list of 3 rows and 4 columns
print("Example two: ")

lst1 = [10, 20, 30, 40]
lst2 = [50, 60, 70, 80]
lst3 = [90, 100, 110, 120]

arr_2d = np.array([lst1, lst2, lst3])
print(arr_2d)
print(type(arr_2d))  # type of array
print("Dimension: ",arr_2d.ndim)   #  Dimension of array

NumPy 2-d Array Creation: 
Example one: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Type      :  <class 'numpy.ndarray'>
Dimension :  2
Example two: 
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
<class 'numpy.ndarray'>
Dimension:  2


In [10]:
''' 
4. Create a 3-D NumPy Array
    - A 3D array is a collection of 2D arrays. 
    - A 3D array is represented in the form of three subscripts([[ [] ]]]).
    - it can be represented in the form of depth, rows, columns.
    - extend the concept of two dimensions array.
  


 syntax:
    arr_3d = np.array(object, dtype = None)


'''
# eg_01: create a 3D array with 2 "slices", each of 3 rows and 3 columns

print("NumPy 3-d Array Creation: ")


print("Example one: ")
arr_3d = np.array([ [
    [1, 2, 1],
    [3, 2, 1],      # this is the slice 1
    [4, 2, 1]],
    
    [[10, 20, 10],
    [ 30, 20, 10],   # this is the slice 2
    [ 40, 20, 10]] ])


print(arr_3d)

print("Type     : ",type(arr_3d))
print("Dimension: ", arr_3d.ndim)


# eg_02: create a 3D array with 3 slices(depth), each of 2 rows and 3 columns
print("\nExample two: ")

arr2_3d = np.array([ 
    [[11, 12, 13],
    [21, 22, 23]],  # this is the slice one

    [[31, 32, 33],
    [41, 42, 43]],  # this is the slice two

    [[51, 52, 53],
    [61, 62, 63]]  ]) # this is the slice three




print(arr2_3d)
print("Dimension :",arr2_3d.ndim)



NumPy 3-d Array Creation: 
Example one: 
[[[ 1  2  1]
  [ 3  2  1]
  [ 4  2  1]]

 [[10 20 10]
  [30 20 10]
  [40 20 10]]]
Type     :  <class 'numpy.ndarray'>
Dimension:  3

Example two: 
[[[11 12 13]
  [21 22 23]]

 [[31 32 33]
  [41 42 43]]

 [[51 52 53]
  [61 62 63]]]
Dimension : 3


1.7 : NumPy Array Attributes
-----------------------------

   - Provide useful information about the array, such as its shape, size, data type, memory layout, and more.

   - Common NumPy Attributes
        - ndim     : Number of dimensions

        - shape    : Shape of the array
        
        - size     : Total number of elements in the array
        
        - Len      : Length of the array
        
        - dtype    : Data type of array elements
        
        - itemsize : Size of each element in bytes
        
        - nbytes   : Total size of the array in bytes or Total memory size in bytes
        
        - strides  : Strides of the array in bytes (for each dimension)
        

In [11]:
#  for one dimension array(vector)

# ndim  : 1-d array dimensions = 1
# shape : 1-d array no. of elements in array
# size  : total no. of elements in the array

print("NumPy Array Attributes for 1-d array")

import numpy as np

print("Example one : ")
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

print("Type     : ",type(arr_1d))   # type of the array

print("Dimension: ",arr_1d.ndim)    # dimension of the array

print("Shape    : ",arr_1d.shape)   # shape of the array (for 1-d array contain the number of elements in the array)

print("size     : ",arr_1d.size)    # size of the array

print("length   :",len(arr_1d))   # length of the array

print(arr_1d.dtype=='float32') # to check the data type is float32 or not of the array
print("Data type: ",arr_1d.dtype)            # find the actual data type of the array
print(arr_1d.dtype=='int64')   # to check the data type is int64 or not  data type of the array


print("individual Item size: ",arr_1d.itemsize) # each element occupies 8 bytes

print("Totla array size: ",arr_1d.nbytes) # total size of the array in bytes or total memory occupied by the array (number of element * itemsize)
                                                                                              # =>  5 * 8 = 40 bytes


print("individual Item size: ",arr_1d.nbytes/arr_1d.itemsize) # size of the array
                                

NumPy Array Attributes for 1-d array
Example one : 
[1 2 3 4 5]
Type     :  <class 'numpy.ndarray'>
Dimension:  1
Shape    :  (5,)
size     :  5
length   : 5
False
Data type:  int64
True
individual Item size:  8
Totla array size:  40
individual Item size:  5.0


In [12]:
#  for two dimension array(matrix)

# 2-d array dimensions = 2
# shape : 2-d array no. of rows and columns
# size  : total no. of elements in the array (rows * columns)

print("NumPy Array Attributes for 2-d array")

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Example one : ")
print(arr_2d)

print("Type   :", type(arr_2d))   # type of the array

print("Dimension:", arr_2d.ndim)    # number of dimensions

print("Shape   : ",arr_2d.shape)   # shape of the array (rows, columns)

print("Size    : ",arr_2d.size)    # size of the array (rows * columns) => 3 * 3 = 9 size(elements) or dimension multiplications

print("length  :",len(arr_2d))   # length of the array(counts the number of rows)

print("Data type: ",arr_2d.dtype=='float32') # to check the data type is float32 or not

print("Data type: ",arr_2d.dtype)            # find the actual data type of the array
print(arr_2d.dtype=='int64')   # to check the data type is int64 or not  data type of the array

print("individual Item size: ",arr_2d.itemsize) # each element occupies 8 bytes

print("Totla array size: ",arr_2d.nbytes) # total size of the array in bytes or total memory occupied by the array (number of element * itemsize)
                                                                                              # => 9  * 8 = 72 bytes




NumPy Array Attributes for 2-d array
Example one : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Type   : <class 'numpy.ndarray'>
Dimension: 2
Shape   :  (3, 3)
Size    :  9
length  : 3
Data type:  False
Data type:  int64
True
individual Item size:  8
Totla array size:  72


In [14]:
#  for three dimension array

# 3-d array dimensions = 3
# shape : 3-d array no. of slices(depth), each slices rows, each slice columns
# size  : total no. of elements in the array (depth * rows * columns)

print("NumPy Array Attributes for 3-d array ")


arr_3d = np.array([
                 [[1, 2, 3],
                 [4, 5, 6], 
                 [7, 8, 9]], 
                 
                 [[10, 11, 12],
                 [13, 14, 15], 
                 [16, 17, 18]]
                 ])

print("Example one : ")
print(arr_3d)

print("Type   :", type(arr_3d))   # type of the array

print("Dimension:", arr_3d.ndim)    # number of dimensions(only single number)

print("Shape: ", arr_3d.shape)   # shape of the array [ slices(depth), each slices rows, each slice columns]

print("Size    : ",arr_3d.size)    # size of the array (depth * rows * columns) => 2 * 3 * 3 = 18 size(elements)

print("length  :",len(arr_3d))   # length of the array(counts the number of depths or slices) => 2


print("Data type: ",arr_3d.dtype)            # find the actual data type of the array


print("individual Item size: ",arr_3d.itemsize, "Byte") # each element occupies 8 bytes

print("total array size: ",arr_3d.nbytes, "Byte") # total size of the array in bytes or total memory occupied by the array (number of element * itemsize)
                                                                                              # => 18 * 8   = 144 bytes

NumPy Array Attributes for 3-d array 
Example one : 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
Type   : <class 'numpy.ndarray'>
Dimension: 3
Shape:  (2, 3, 3)
Size    :  18
length  : 2
Data type:  int64
individual Item size:  8 Byte
total array size:  144 Byte
