Creating N-d Arrays by using Functions

- most common functions

    - np.empty() : returns np.empty array(which is near to zero)
    
    - np.zeros() : create N-D array with initialization zeros and specified shape	

    - np.ones()  : create N-D array with initialization ones with a specified shape

    - np.full()  : create N-D array with a specified value with a specified shape

    - np.arange(): create N-D array of a specified Range of values, can reshape to multidimensional

    - np.linspace(): create N-D array of evenly spaced values, can be reshaped

    - np.random.rand(): create Array with random values (0-1)
    
    - np.random.randint(): create Array with random integers in a specified range

    - np.eye() : Creates array Identity matrix


In [ ]:
# For 1-d arrays(Vector)
import numpy as np

print("1-d array creation with initialization \n")
# Creating a 1-d array of zeros
print("Creating a 1-d array of zeros")
arr1_1d = np.zeros(5) # 5 = total number of elements
print(arr1_1d)

print("Creating a 2-d array of ones")
# Creating a 1-d array of ones
print("Example One: ")
arr2_1d = np.ones(5)   # 5 = total number of elements and default data type is float
print(arr2_1d)

print("Example Two: ")
arr21_1d = np.ones(6, dtype=int)  # 6 = total number of elements and modify the default data type
print(arr21_1d)

# Creating a 1-d array of a specified value
print("Creation 1-d array with specified value")

print("Example One: ")
arr3_1d = np.full(5, 100)   #  here, 5 = times , 100 = values
print(arr3_1d)

# Creating a 1-d array of a specified range
print("Creation 1-d array with specified range")

print("Example One: ")
arr4_1d = np.arange(5) # star with 0 and end with length - 1, (length = 5)
print(arr4_1d)

# Creating a 1-d array of evenly spaced values
print("Creation 1-d array with evenly spaced values")

print("Example One: ")
arr5_1d = np.linspace(1, 2, 5)  # stat element = 1  end element = 2 ,  number of elements = 5
print(arr5_1d)

# Creating a 1-d array with random values (0-1)
print("Creation 1-d array with random values(0-1)")

print("Example One: ")
arr6_1d = np.random.rand(5)  # total 5 random elements in between 0 to 1
print(arr6_1d)

# Creating a 1-d array with random integers in a specified range
print("Creation 1-d array with random integers")

print("Example One: ")
arr7_1d = np.random.randint(1, 10, 5) # start and end element in between 1-10 and number of elements = 5
print(arr7_1d)



print("Type: ",type(arr7_1d))
print("Dimension of array: ",arr7_1d.ndim) # dimension of the array





1-d array creation with initialization 

Creating a 1-d array of zeros
[0. 0. 0. 0. 0.]
Creating a 2-d array of ones
Example One: 
[1. 1. 1. 1. 1.]
Example Two: 
[1 1 1 1 1 1]
Creation 1-d array with specified value
Example One: 
[100 100 100 100 100]
Creation 1-d array with specified range
Example One: 
[0 1 2 3 4]
Creation 1-d array with evenly spaced values
Example One: 
[1.   1.25 1.5  1.75 2.  ]
Creation 1-d array with random values(0-1)
Example One: 
[0.13566181 0.25226939 0.37266288 0.09343668 0.63210702]
Creation 1-d array with random integers
Example One: 
[4 7 5 2 2]
Type:  <class 'numpy.ndarray'>
Dimension of array:  1


In [ ]:
# For 2-d arrays(Matrix)
print("2-d array creation with initialization \n")
print("Example one: 2-d array creation with initialization empty(near to zero)")
arr = np.empty((3,4))
print(arr)
# Creating a 2-d array of zeros
print("Example two: 2-d array creation with initialization zeros")
arr = np.zeros((3, 3))    #  rows = 3, columns = 3
print(arr)

# Creating a 2-d array of ones
print("Example three :2-d array creation with initialization ones")
arr = np.ones((3, 4))    #  rows = 3, columns = 4
print(arr)

# Creating a 2-d array of a specified value
print("Example Four : 2-d array creation with initialization specified value")
arr = np.full((2, 2), 5)    #  rows = 2, columns = 2, values 5
print(arr)

# Creating a 2-d array of a specified range
print("Example Five : 2-d array creation with initialization specified range")
arr1 = np.arange(3, 11).reshape(2,4)  # rows = 2, columns = 4 ## if reshape cant't maintain dimension then it gives error.
print(arr1)


# Creating a 2-d array of evenly spaced values
print("Example Six : 2-d array creation with initialization evenly spaced values")
arr2 = np.linspace(2, 20, 10).reshape(5,2) # here step size is automatically determined 
print(arr2)       # 2 = start number , 20 = end number and 10 = total number , 5 = rows, 2 = columns and interval between start and end values is automatically determined

# Creating a 2-d array with random values (0-1)
print("Example Seven : 2-d array creation with initialization random values(0-1) ")
arr = np.random.rand(3, 4)  # rows = 3, columns = 4
print(arr)

# Creating a 2-d array with random integers in a specified range
print("Example Eight : 2-d array creation with initialization random integers ")
arr = np.random.randint(3, 10, (3, 4))  # star and end in between 3 5o 10 and rows = 3, columns = 4
print(arr)

print("Example : Create a identity matrix")
arr = np.eye(3,3)
print(arr)

print("Dimension of array: ",arr.ndim)

2-d array creation with initialization 

Example one: 2-d array creation with initialization empty(near to zero)
[[3.e-323 3.e-323 3.e-323 3.e-323]
 [3.e-323 3.e-323 3.e-323 3.e-323]
 [3.e-323 3.e-323 3.e-323 3.e-323]]
Example two: 2-d array creation with initialization zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Example three :2-d array creation with initialization ones
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Example Four : 2-d array creation with initialization specified value
[[5 5]
 [5 5]]
Example Five : 2-d array creation with initialization specified range
[[ 3  4  5  6]
 [ 7  8  9 10]]
Example Six : 2-d array creation with initialization evenly spaced values
[[ 2.  4.]
 [ 6.  8.]
 [10. 12.]
 [14. 16.]
 [18. 20.]]
Example Seven : 2-d array creation with initialization random values(0-1) 
[[0.17315685 0.96869237 0.13667147 0.39513431]
 [0.04236865 0.54406625 0.1775608  0.88852327]
 [0.65063506 0.97628989 0.02965871 0.21139538]]
Example Eight : 2-d array creation with initiali

In [53]:
print("3-d array creation with initialization \n")

# Creating a 3-d array of zeros
print("Example one: empty 3-d array creation ")
arr3 = np.empty((2,3,3))   # e power -309(something) this is near to zero that way we count it is empty
print(arr3)

print("\nExample two: create 3-d array with initial values zero")
arr31 = np.zeros((2,3,4))   # 2 = depth, 3 = each depth row number , 4 = each depth column number.
print(arr31)

print("\nExample three: 3-d array creation with initial values one")
arr32 = np.ones((3, 2,3))
print(arr32)

print("\nExample four: 3-d array creation with initial values specified value")
arr33 = np.full((2,3,2),6)   # 2 = depth , 3 = each depth row number , 2 = each depth column number and 6 = specific value(element)
print(arr33)

print("\nExample five: 3-d array creation with initial values specified range")
arr34 = np.arange(1,25).reshape(2,6,2)  # number in range = 1 to 25 , 2 = depth, 6 = each depth row number , 2 = each depth column number
print(arr34)

print("\nExample six: 3-d array creation with initial values evenly spaced values")
arr35 = np.linspace(1, 20,10 ).reshape(1,5,2) 
print(arr35)     # start element = 1 , end element = 20 , total number of elements = 10
                 # depth = 1, 5 = each depth row number , 2 = each depth column number
                 # depth * rows * columns = total number of elements
                 # => 1 * 5 * 2 = 10 (which is the total number of elements)
                 # here step size is automatically calculated 

print("\nExample seven: 3-d array creation with initial values random values(0-1)")
arr36 = np.random.rand(2,3,3) # 2 = depth, 3 = each depth row number , 3 = each depth column number
print(arr36)

print("\nExample eight: 3-d array creation with initial values random integers")
arr37 = np.random.randint(1, 10, (2,3,3)) # 2 = depth, 3 = each depth row number , 3 = each depth column number
print(arr37)     # within 1 to 10 create 18 random integers



3-d array creation with initialization 

Example one: empty 3-d array creation 
[[[0.69206947 0.96450842 0.31173204]
  [0.57743958 0.3930673  0.98684579]
  [0.77661587 0.44811612 0.22700053]]

 [[0.4530563  0.34531836 0.24988568]
  [0.27028614 0.22847178 0.39402715]
  [0.49661051 0.81322171 0.76482709]]]

Example two: create 3-d array with initial values zero
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

Example three: 3-d array creation with initial values one
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

Example four: 3-d array creation with initial values specified value
[[[6 6]
  [6 6]
  [6 6]]

 [[6 6]
  [6 6]
  [6 6]]]

Example five: 3-d array creation with initial values specified range
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]
  [19 20]
  [21 22]
  [23 24]]]

Example six: 3-d array creation with initial values evenly spaced values
[[[ 1