Outcome:
      - 3.1 changing data types
      - 3.2 Reshaping and convert 1-d, 2-d, 3-d arrays
      - 3.3 stacking 
      - 3.4 splitting


In [ ]:
'''  
 3.1  Changing data types
 --------------------------
 Different data types consume different amounts of memory

        int8  uses 1 byte per element
        int16 uses 2 bytes per element
        int32 uses 4 bytes per element.
        int64 uses 8 bytes per element.
        float64 uses 8 bytes, while float32 uses 4 bytes.

** To Optimize Memory Usage then we need to change the data types.

- there are several different ways to change the data type of an array.
      - dtype
      - astype()


'''

# Example one: using dtype to reduces memory usage
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print("Data type : ",arr1.dtype)  # data type by default

# memory usage
print("Each item occupies memory: ", arr1.itemsize)
print("Total memory usage: ",arr1.nbytes)

# to convert default data type
arr2 = np.array([1, 2, 3, 4, 5], dtype=np.int8) 
print(arr2)
print("Data type : ",arr2.dtype)  # o/p: int8 (we know int8 is 1 byte)
print("Each item memory usage :", arr2.itemsize) 
print("Total memory usage: ",arr2.nbytes)  # memory usage reduced



[1 2 3 4 5]
Data type :  int64
Each item occupies memory:  8
Total memory usage:  40
[1 2 3 4 5]
Data type :  int8
Each item memory usage : 1
Total memory usage:  5


In [ ]:
# example two : using astype():
print("Default array")
arr3 = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(arr3)
print("Default data type : ",arr3.dtype)   # default data type
print("individual element memory occupied  : ", arr3.itemsize, "Bytes")
print("total array memory occupied  : ", arr3.nbytes, "Bytes")


# to convert default data type
print("\nConvert default data type")
arr3 = arr3.astype(np.float32)  # float32 is 4 bytes

print(arr3)
print("Data type : ",arr3.dtype)
print("each item memory usage : ",arr3.itemsize)
print("Total array memory occupied  : ",arr3.nbytes)

Default array
[10 20 30 40 50 60 70 80]
Default data type :  int64
individual element memory occupied  :  8 Bytes
total array memory occupied  :  64 Bytes

Convert default data type
[10. 20. 30. 40. 50. 60. 70. 80.]
Data type :  float32
each item memory usage :  4
Total array memory occupied  :  32


- 3.2 Reshaping and convert 1-d, 2-d, 3-d arrays and vice versa 
     ------------------------------------------------------------
     - Changing the structure of an array without altering it's data.
     - after reshaping an array number of elements are same.
     - By using reshaping we can change the dimensions of the array


     - There are several way to reshape an array
            -> reshape()
            -> Transpose() or array_name.T
            -> ravel()


In [ ]:
# example one: using reshape():

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original array : ",arr1)
print("Original array shape : ",arr1.shape) # Total number of elements in original array(9)

# reshape to 3x3 array
arr1_reshaped = arr1.reshape(3,3)   # 3 = rows and 3 = columns so total number of elements = 3 * 3 = 9. so after reshaping the number of elements are same
print("Reshaped array : \n",arr1_reshaped)
print("Array shape: ", arr1_reshaped.shape) # o/p: (3,3)

# we also reshape arr1 in : (9,1) and (1,9) shape.
arr1_reshaped = arr1.reshape(9,1)   # 9 = rows and 1 = columns , total nums of elements(9*1 = 9)
print("Reshaped array : \n",arr1_reshaped)
print("Reshaped array shape: ", arr1_reshaped.shape) # o/p: (9,1)

# reshaping with -1
arr1_res = arr1.reshape(3,-1) # rows = 3 and columns = automatically calculated
print("Reshaped array with -1 : \n",arr1_res)

Original array :  [1 2 3 4 5 6 7 8 9]
Original array shape :  (9,)
Reshaped array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array shape:  (3, 3)
Reshaped array : 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Reshaped array shape:  (9, 1)
Reshaped array with -1 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Example two: using reshaping to convert 1-d, 2-d, 3-d arrays

# 1-d array
arr1 = np.arange(1,13)  # here total elements = 12

print("Original 1-d array : \n",arr1)
print("Dimension : ",arr1.ndim)

# to convert to 2-d array
arr2 = arr1.reshape(4,3)   # 4 = rows and 3 = columns (4*3 = 12)
print("To convert 1-d to 2-d array: \n", arr2)
print("Dimension : ",arr2.ndim)

# to convert to 3-d array
arr3 = arr1.reshape(2,2,3) # 2 = depth of array , 2 = each depth rows ans 3 = each depth columns(2*2*3 = 12)

print("To convert 1-d to 3-d array: \n", arr3)

print("Dimension : ",arr3.ndim)

Original 1-d array : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension :  1
To convert 1-d to 2-d array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Dimension :  2
To convert 1-d to 3-d array: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension :  3


In [ ]:
# Example three: convert 3-d to 2-d, 1-d array using reshaping(NNB_cds: After reshaping total nums of elements will be same)
arr3 = np.arange(1,25).reshape(2,3,4)  # total elements (2*3*4) = 24
print("3-d array: \n",arr3)
print("Dimension : ",arr3.ndim)

# convert to 2-d array
arr2 = arr3.reshape(6,4)  # 6 = rows and 4 = columns (6*4 = 24)
print("To convert 3-d to 2-d array: \n", arr2)
print("Dimension : ",arr2.ndim)

# convert to 1-d array
arr1 = arr2.reshape(24)  # 24 = total number of elements
print("To convert 2-d to 1-d array: \n", arr1)

print("Dimension : ",arr1.ndim)

3-d array: 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Dimension :  3
To convert 3-d to 2-d array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Dimension :  2
To convert 2-d to 1-d array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Dimension :  1


In [49]:
# Example four :  convert 3-d to 2-d, 1-d array using reshaping
arr2 = np.arange(10,50,2).reshape(4,5) # total number of elements (4*5) = 20
print("Original 2-d array: \n",arr2)
print("Dimension : ",arr2.ndim)

# convert to 1-d array
arr1 = arr2.reshape(20)  # 20 = total number of elements
print("\n1-d array: ",arr1)
print("Dimension : ",arr1.ndim)


# convert to 3-d array
arr3 = arr1.reshape(2,2,5)  # 2 = depth of array , 2 = each depth rows ans 5 = each depth columns(2*2*5 = 20)
print("\n3-d array: \n", arr3)

print("Dimension : ",arr3.ndim)

Original 2-d array: 
 [[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]
Dimension :  2

1-d array:  [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
Dimension :  1

3-d array: 
 [[[10 12 14 16 18]
  [20 22 24 26 28]]

 [[30 32 34 36 38]
  [40 42 44 46 48]]]
Dimension :  3


In [ ]:
# Reshaping using transpose : to convert row to columns and vice versa
arr1 = np.arange(1,13).reshape(3,4)  # here total elements = 12

print("Original array : \n",arr1)
print("Dimension : ",arr1.ndim)

# using transpose to swap rows to columns or vice versa
trans_arr1 = np.transpose(arr1) 
print("Transpose array : \n", trans_arr1)

# using array.T   # must 'T' is capital letter
arr1 = arr1.T     
print("Transpose array(.T): \n",arr1)

Original array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimension :  2
Transpose array : 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Transpose array(.T): 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [95]:
'''  
# using ravel : use to change a multi-dimensional array into a 1-d array

- Syntax:
      arr_name.ravel()
---------------
'''
arr2 = np.arange(1,11).reshape(2,5)
print("Original 2-d array: \n",arr2)
print("Dimension : ",arr2.ndim)

# using ravel to convert to 1-d array
arr1 = arr2.ravel()
print("Ravel 1-d array: \n",arr1)
print("Dimension : ",arr1.ndim)


# example 2: create a 3-d array 
arr = np.arange(2,98,4)
print("Total number of elements: ",arr.size)


arr3 = np.arange(2,98,4).reshape(3,2,4)
print("Original 3-d array: \n",arr3)

# using ravel to convert to 1-d array
arr1 = arr3.ravel()

print("Ravel 1-d array: \n",arr1)


Original 2-d array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dimension :  2
Ravel 1-d array: 
 [ 1  2  3  4  5  6  7  8  9 10]
Dimension :  1
Total number of elements:  24
Original 3-d array: 
 [[[ 2  6 10 14]
  [18 22 26 30]]

 [[34 38 42 46]
  [50 54 58 62]]

 [[66 70 74 78]
  [82 86 90 94]]]
Ravel 1-d array: 
 [ 2  6 10 14 18 22 26 30 34 38 42 46 50 54 58 62 66 70 74 78 82 86 90 94]


- 3.3 stacking 
    -----------
   -  refers to combining multiple arrays along a new axis
   - type:
      >> np.stack(arr1,arr2, axis=0) * 
      >> np.hstack(arr1,arr2)  * *
      >> np.vstack(arr1,arr2)  * *
      >> np.dstack(arr1,arr2)  * * *
      >> np.concatenate((arr1,arr2),axis=0)
      >> np.column_stack(arr1,arr2)
      >> np.row_stack(arr1,arr2)

In [ ]:
"""  
example one: use np.stack((arr1,arr2),axis = 0)  # 0 = cols way(vertical order)
------------------------------------------------
    - To combine multiple arrays
    - condition: all arrays must have the same shape

"""
arr1 = np.arange(10, 50,2)
print("Total elements: ",arr1.shape)  # total elements
arr1 = np.arange(10, 50,2).reshape(4,5)
print("Array one: \n",arr1)

arr2 = np.arange(60, 100,2).reshape(4,5)
print("Array two: \n",arr2)

arr3 = np.stack((arr1, arr2), axis = 0) # 0 = cols way(horizontal order), 1 = rows way(vertical order)
print("arr3: \n",arr3)
   

Total elements:  (20,)
Array one: 
 [[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]
Array two: 
 [[60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]
arr3: 
 [[[10 12 14 16 18]
  [60 62 64 66 68]]

 [[20 22 24 26 28]
  [70 72 74 76 78]]

 [[30 32 34 36 38]
  [80 82 84 86 88]]

 [[40 42 44 46 48]
  [90 92 94 96 98]]]
